doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    'DoctrineMigrations\Tourney\Vot': "%kernel.project_dir%/migrations/Tourney/Vot"
    'DoctrineMigrations\Tourney\Vtc': "%kernel.project_dir%/migrations/Tourney/Vtc"
    'DoctrineMigrations\Web': "%kernel.project_dir%/migrations/Web"

  all_or_nothing: true
  transactional: true
  check_database_platform: true
  organize_migrations: none

  enable_profiler: false
