doctrine:
  dbal:
    # NOTE:
    # I prefer explicit rather than implicit, hence why these variables are here
    driver: "%env(DB_DRIVER)%"
    user: "%env(DB_USER)%"
    password: "%env(DB_PASSWORD)%"
    host: "%env(DB_HOST)%"
    port: "%env(DB_PORT)%"
    dbname: "%env(DB_NAME)%"
    server_version: "%env(DB_SERVER_VERSION)%"
    charset: "%env(DB_CHARSET)%"

    profiling_collect_backtrace: "%kernel.debug%"

  orm:
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    identity_generation_preferences:
      Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
    auto_mapping: true
    mappings:
      Catalog:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity/Catalog"
        prefix: 'App\Entity\Catalog'
        alias: Catalog
      Tourney:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity/Tourney"
        prefix: 'App\Entity\Tourney'
        alias: Tourney
      Web:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity/Web"
        prefix: 'App\Entity\Web'
        alias: Web

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
