services:
  # PHP-FPM container
  vot-app:
    container_name: # Optional. You may leave this empty, which Docker will give a default name for the container automatically
    networks:
      - # Optional. You may delete this element if only building for one specific PHP version
    build:
      context: .
      dockerfile: docker/php/php.${ENV}.Dockerfile
    volumes:
      - ./src/private/vendor:/var/www/html/private/vendor # Optional. You may omit this if you don't mind Composer packages load a bit slower on start-up
      - ./src:/var/www/html # Optional. You may omit this if build for production stage
    restart: unless-stopped # Optional. You may let this be 'always' in all stages

  # NGINX container
  vot-web:
   container_name: # Optional. You may leave this empty, which Docker will give a default name for the container automatically
    networks:
      - # Optional. You may delete this element if only building for one specific PHP version
    depends_on:
      - vot-app   # Required. Need PHP modules first to get the website working
      - vot-db    # Required. Need MariaDB database second to be able to do CRUD process
    build:
      context: .
      dockerfile: docker/nginx/nginx.${ENV}.Dockerfile
    volumes:
      - ./src:/var/www/html # Optional. You may omit this if build for production stage
    ports:
      # Optional. Only use for development stage, omit on production stage as it contains security issues
      - "<any-ports>:80"  # HTTP
      - "<any-ports>:443" # HTTPS (or SSL/TLS)
    restart: unless-stopped # Optional. You may let this be 'always' in all stages

  # MariaDB container
  vot-db:
   container_name: # Optional. You may leave this empty, which Docker will give a default name for the container automatically
    networks:
      - # Optional. You may delete this element if only building for one specific PHP version
    build:
      context: .
      dockerfile: docker/sql/mariadb.${ENV}.Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql # Per common practice but we will be loading backed-up data constantly on prduction stage
    ports:
      # Optional. Only use for development stage, omit on production stage (or use 'phpmyadmin') as it contains security issues
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: unless-stopped # Optional. You may let this be 'always' in all stages

# Per common practice but we will be loading backed-up data constantly on prduction stage
volumes:
  mariadb_data:
    name: # Optional. You may leave this empty, which Docker will give a default name for the container automatically

# Optional. As metioned above, only use if working with multiple PHP versions
#networks:
#  vot-network:
#    name: vot-dev-network
#    driver: bridge
