# Docker-specific configs
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

# API and dashboard configs
api:
  dashboard: true
  insecure: false

# Entry-point configs
entryPoints:
  web:
    address: ":80"

# Log configs
accessLog:
  format: "common"
